# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # The OS of the virtual machine / docker container
    # github performs our actions on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      postgresql:
        image: 'postgres:12'
        ports:
          - '54320:5432'
        env:
          POSTGRES_DB: example_app_test_db
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: example_app_db_test_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Checkout our branch in the container
    - name: Checkout ğŸ›
      uses: actions/checkout@v2

    # Download and setup nodejs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
      run: npm ci

    - name: Run migrations
      run: npm run migrate -- --env test

    - name: run end-to-end tests ğŸ§ª
      run: npm run test
    

    
